global:
  scrape_interval: 15s        #Chu kỳ Prometheus thu thập dữ liệu (15 giây/lần).
  evaluation_interval: 15s     #đánh giá các rule cảnh báo

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:8080']
        labels:
          instance: 'node-app-local'
    metrics_path: /metrics

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
  # kiểm tra uptime của node-app
    static_configs:
      - targets:
          - http://node-app:8080/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
